### PR TITLE
fix: reverse the order of stacking and put bottomsheet at the root to enable navigating to bottom sheet

### PR DESCRIPTION
**Pull request by dannyhw**
issue: #2 

If you make the root layout the bottomsheet then the stack as the child then it seems to work

image

### CODE REVIEW

**Comment by pvinis** [comment]
Mmmm I see I see. Ok, no issues with the reversing.

But according to the readme, the goal for the bottom sheet is to have the `other` screen be part of that same bottom sheet, ideally in a stack. When I try it here, I see that the bottom sheet goes away and another one comes up.


https://github.com/user-attachments/assets/759ded26-b4da-42e3-a711-a1ec820c8a31

Do you have any ideas? I'll also play around.

**Comment by dannyhw** [comment]
I guess then you need to have a stack inside the bottomsheet like instead of the index screen its another folder with a stack layout inside and the index and other screen in there

Not sure if a native stack would work there, maybe

Can try it in a bit

**Comment by pvinis** [comment]
This is where I'm at:
https://github.com/user-attachments/assets/146ee734-d7b9-4191-896e-d18fa38a16b3

lol.

No rush, but I'd love to see what you will be able to make!

**Comment by dannyhw** [comment]
latest version has navigation inside the bottom sheet but since its using slot doesn't have animations yet, still trying some stuff

https://github.com/user-attachments/assets/34b13b4b-59af-4f8c-a871-b781dcb9fdfa

**Comment by dannyhw** [comment]
ok here it is with a proper js stack navigator

https://github.com/user-attachments/assets/e5e5f759-2540-4b33-9857-164425333980

**Comment by dannyhw** [comment]
@pvinis how about this latest version?

**Comment by pvinis** [comment]
Oh snap! That last one looks like the solution. I'll take a look at the code and talk to you for the bounty.

**Comment by pvinis** [comment]
Ok it actually works great!! Thank you so much! 💜 Let me know if you prefer to get the bounty with [this opire reward](https://app.opire.dev/issues/01JAAPWX64AQ5BJQ4TQAJJ96GP) or some other way (gh sponsor or revolut or crypto or whatever else).


PS. It will be fun for me to try to play and move things around, to see how they break or work, starting from your code here (which I'll merge so I have a better starting point for future trials). I want to also add a drawer on the side, and I had that working at some point, so I'll try to put all of them in one.

**Comment by dannyhw** [comment]
Glad I could help :). I had a lot of battles with expo router configuration when I was first setting it up, so you're not alone in that. Sometimes it just works in ways that don't seem intuitive unfortunately.

Revolut sounds good to me.

https://revolut.me/danielx96

Heres my contact in case you need it

dannyhyunsoowilliams@gmail.com
https://twitter.com/Danny_H_W

**Comment by pvinis** [comment]
Bounty sent!

Thank you for your work, you're awesome!

**Pull request merged**
